name: Deploy to Azure Web App - My Daily Planner

on:
  push:
    branches:
      - master  # or main, depending on your repo's default

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Zip static site content
      run: |
        mkdir build
        cp index.html build/
        cd build
        zip -r ../app.zip .

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mytestwebapp1234NEW'  # your Azure Web App name
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: app.zip

